#!/usr/bin/env bash
#
# Portal Device DB — capability collector
# ---------------------------------------
# Pulls a STANDARDIZED, read-only snapshot of a Meta Portal device over ADB so
# the community can map what each model / OS build / launcher version can do.
#
# It changes NOTHING on the device (no grants, no installs) and does NOT collect
# your serial number or any personal data — just hardware/OS/permission facts.
#
# Usage:
#   1. Enable ADB on the Portal (Settings → it varies by launcher; Immortal has a toggle)
#   2. Plug it into a computer (or use wireless adb), confirm `adb devices` shows it
#   3. ./collect.sh            # or  ./collect.sh <adb-serial>  if several devices
#   4. Paste the printed report into a "Device report" issue on the repo, or PR it
#      into reports/.  That's it — thank you for contributing!
#
set -uo pipefail

SERIAL="${1:-}"
ADB=(adb); [ -n "$SERIAL" ] && ADB=(adb -s "$SERIAL")

# Bail early with a friendly message if no device is reachable.
if ! "${ADB[@]}" get-state >/dev/null 2>&1; then
  echo "No ADB device reachable. Enable ADB on the Portal, plug it in, and check 'adb devices'." >&2
  exit 1
fi

sh()  { "${ADB[@]}" shell "$@" 2>/dev/null | tr -d '\r'; }
prop(){ sh "getprop $1"; }
have(){ sh "pm list packages $1" | grep -q . && echo yes || echo no; }
ver() { sh "dumpsys package $1 | grep -m1 versionName" | sed 's/.*versionName=//'; }

MODEL="$(prop ro.product.model)"
DEVICE="$(prop ro.product.device)"
BUILD="$(prop ro.build.fingerprint)"
SLUG="$(echo "${MODEL}-${DEVICE}" | tr ' /' '--' | tr -cd 'A-Za-z0-9._-')"
OUT="reports/${SLUG}.md"

# ---- permission census: categorise all platform permissions by reachability ----
# A sideloaded app can obtain: normal (auto) + dangerous (runtime). A 'development'
# flag means adb `pm grant` works (the elevated set). Everything else is a wall.
PERMS="$(sh 'dumpsys package permissions' | awk '
  /Permission \[/ { n=$0; sub(/.*Permission \[/,"",n); sub(/\].*/,"",n) }
  /prot=/         { p=$0; sub(/.*prot=/,"",p); if(n!=""){print n"\t"p; n=""} }')"
pc()    { echo "$PERMS" | awk -F'\t' "$1" | wc -l | tr -d ' '; }
N_TOTAL=$(echo "$PERMS" | grep -c . )
N_NORMAL=$(pc '$2 ~ /(^|\|)normal/')
N_DANGER=$(pc '$2 ~ /(^|\|)dangerous/')
N_DEV=$(pc '$2 ~ /development/')
N_WALL=$(pc '$2 !~ /normal|dangerous|development/')
DEV_LIST="$(echo "$PERMS" | awk -F'\t' '$2 ~ /development/ {print "  - `"$1"` ("$2")"}' | sort)"

write() { echo "$1" >> "$OUT"; }
: > "$OUT"

write "# ${MODEL} — device report"
write ""
write "_Generated by \`collect.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')_  ·  read-only, no serial collected."
write ""
write "## Identity"
write "| | |"
write "|---|---|"
write "| Model | \`${MODEL}\` |"
write "| Codename | \`${DEVICE}\` |"
write "| Android | $(prop ro.build.version.release) (API $(prop ro.build.version.sdk)) |"
write "| Build | \`${BUILD}\` |"
write "| Security patch | $(prop ro.build.version.security_patch) |"
write "| HW revision | rev $(prop ro.boot.revision) |"
write "| ABIs | $(prop ro.product.cpu.abilist) |"
write "| SoC | $(prop ro.board.platform) / $(prop ro.hardware) |"
write ""
write "## Hardware"
write "| | |"
write "|---|---|"
write "| RAM | $(sh 'grep MemTotal /proc/meminfo' | awk '{printf "%.1f GB", $2/1048576}') |"
write "| Display | $(sh 'wm size' | sed 's/.*: //') @ $(sh 'wm density' | sed 's/.*: //') dpi |"
write "| Data partition | $(sh 'df /data | tail -1' | awk '{printf "%.1f GB total, %.1f GB free", $2/1048576, $4/1048576}') |"
write "| Auto-rotation | $(sh 'dumpsys window | grep -m1 mSupportAutoRotation' | sed 's/^ *//') |"
write ""
write "## Software & security"
write "| | |"
write "|---|---|"
write "| Launcher (Immortal) | $(ver com.immortal.launcher || echo 'not installed') |"
write "| Aloha launcher | $(ver com.facebook.alohaapps.launcher) |"
write "| Google Play Services | $(have com.google.android.gms) |"
write "| Aurora Store | $(have com.aurora.store) |"
write "| Shizuku | $(have moe.shizuku.privileged.api) |"
write "| Bootloader | flash.locked=$(prop ro.boot.flash.locked), verifiedboot=$(prop ro.boot.verifiedbootstate) |"
write "| SELinux | $(sh getenforce) |"
write "| Root (su) | $(sh 'command -v su >/dev/null && echo yes || echo no') |"
write ""
write "## Sensors"
write '```'
sh 'dumpsys sensorservice | grep -oE "android.sensor.[a-z_]+" | sort -u | sed "s/android.sensor.//"' >> "$OUT"
write '```'
write ""
write "## Permission census ($N_TOTAL platform permissions)"
write "What a **sideloaded (non-platform-signed) app** can obtain on this build:"
write ""
write "| Reachability | Count |"
write "|---|---|"
write "| Normal — auto-granted | $N_NORMAL |"
write "| Dangerous — runtime prompt | $N_DANGER |"
write "| **Development — \`adb pm grant\` (elevated)** | **$N_DEV** |"
write "| Signature/privileged walls | $N_WALL |"
write ""
write "<details><summary>The \`development\` (adb-grantable) permissions — the useful elevated set</summary>"
write ""
write "$DEV_LIST"
write ""
write "</details>"
write ""
write "## Active resource overlays (RROs — vendor theming/config)"
write '```'
sh 'cmd overlay list' | grep -E '^\[x\]|^\[ \]' >> "$OUT" 2>/dev/null || sh 'cmd overlay list' >> "$OUT"
write '```'
write ""
write "## Cameras (who holds the hardware)"
write '```'
sh 'dumpsys media.camera | grep -iE "number of (normal )?camera devices:|Device [0-9] maps|Client Package Name" | head -12' >> "$OUT"
write '```'
write ""
write "---"
write "_Submit this file via a \"Device report\" issue or a PR to \`reports/\`. Read-only; no personal data._"

echo "Wrote $OUT"
echo "------------------------------------------------------------------"
cat "$OUT"
