#!/usr/bin/env bash
#
# Portal Device DB — capability collector
# ---------------------------------------
# Pulls a STANDARDIZED, read-only snapshot of a Meta Portal device over ADB so
# the community can map what each model / OS build / launcher version can do.
#
# It changes NOTHING on the device (no grants, no installs) and does NOT collect
# your serial number or any personal data — just hardware/OS/permission facts.
#
# Usage:
#   1. Enable ADB on the Portal (Settings → it varies by launcher; Immortal has a toggle)
#   2. Plug it into a computer (or use wireless adb), confirm `adb devices` shows it
#   3. ./collect.sh            # or  ./collect.sh <adb-serial>  if several devices
#   4. It copies the report to your clipboard and opens a pre-filled GitHub issue —
#      paste it in and click Submit. (It does NOT auto-post; you stay in control.)
#
set -uo pipefail

SERIAL="${1:-}"
ADB=(adb); [ -n "$SERIAL" ] && ADB=(adb -s "$SERIAL")

# Bail early with a friendly message if no device is reachable.
if ! "${ADB[@]}" get-state >/dev/null 2>&1; then
  echo "No ADB device reachable. Enable ADB on the Portal, plug it in, and check 'adb devices'." >&2
  exit 1
fi

sh()  { "${ADB[@]}" shell "$@" 2>/dev/null | tr -d '\r'; }
prop(){ sh "getprop $1"; }
have(){ sh "pm list packages $1" | grep -q . && echo yes || echo no; }
ver() { sh "dumpsys package $1 | grep -m1 versionName" | sed 's/.*versionName=//'; }

MODEL="$(prop ro.product.model)"
DEVICE="$(prop ro.product.device)"
BUILD="$(prop ro.build.fingerprint)"
SLUG="$(echo "${MODEL}-${DEVICE}" | tr ' /' '--' | tr -cd 'A-Za-z0-9._-')"
OUT="reports/${SLUG}.md"

RAM="$(sh 'grep MemTotal /proc/meminfo' | awk '{printf "%.1f GB", $2/1048576}')"
SOC_RAW="$(prop ro.board.platform)"
case "$SOC_RAW" in           # friendly name for the known Portal SoCs
  msm8998) CHIP="Snapdragon 835 (msm8998)";;
  sdm660)  CHIP="Snapdragon 660 (sdm660)";;
  *)       CHIP="${SOC_RAW:-unknown}";;
esac

# ---- permission census: categorise all platform permissions by reachability ----
# A sideloaded app can obtain: normal (auto) + dangerous (runtime). A 'development'
# flag means adb `pm grant` works (the elevated set). Everything else is a wall.
PERMS="$(sh 'dumpsys package permissions' | awk '
  /Permission \[/ { n=$0; sub(/.*Permission \[/,"",n); sub(/\].*/,"",n) }
  /prot=/         { p=$0; sub(/.*prot=/,"",p); if(n!=""){print n"\t"p; n=""} }')"
pc()    { echo "$PERMS" | awk -F'\t' "$1" | wc -l | tr -d ' '; }
N_TOTAL=$(echo "$PERMS" | grep -c . )
N_NORMAL=$(pc '$2 ~ /(^|\|)normal/')
N_DANGER=$(pc '$2 ~ /(^|\|)dangerous/')
N_DEV=$(pc '$2 ~ /development/')
N_WALL=$(pc '$2 !~ /normal|dangerous|development/')
DEV_LIST="$(echo "$PERMS" | awk -F'\t' '$2 ~ /development/ {print "  - `"$1"` ("$2")"}' | sort)"

write() { echo "$1" >> "$OUT"; }
: > "$OUT"

write "# ${MODEL} — device report"
write ""
write "_Generated by \`collect.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')_  ·  read-only, no serial collected."
write ""
write "## Identity"
write "| | |"
write "|---|---|"
write "| Model | \`${MODEL}\` |"
write "| Codename | \`${DEVICE}\` |"
write "| Android | $(prop ro.build.version.release) (API $(prop ro.build.version.sdk)) |"
write "| Build | \`${BUILD}\` |"
write "| Security patch | $(prop ro.build.version.security_patch) |"
write "| HW revision | rev $(prop ro.boot.revision) |"
write "| ABIs | $(prop ro.product.cpu.abilist) |"
write ""
write "## Hardware"
write "| | |"
write "|---|---|"
write "| Chip (SoC) | ${CHIP} |"
write "| RAM | ${RAM} |"
write "| Display | $(sh 'wm size' | sed 's/.*: //') @ $(sh 'wm density' | sed 's/.*: //') dpi |"
write "| Data partition | $(sh 'df /data | tail -1' | awk '{printf "%.1f GB total, %.1f GB free", $2/1048576, $4/1048576}') |"
write "| Auto-rotation supported | $(sh 'dumpsys window | grep -m1 mSupportAutoRotation' | sed 's/^ *//;s/ .*//;s/mSupportAutoRotation=//') |"
write ""
write "## Stock OS & security"
write "_The device's own factory stack + security posture — not anything side-loaded._"
write ""
write "| | |"
write "|---|---|"
write "| Portal system version (Aloha) | $(ver com.facebook.alohaapps.launcher) |"
write "| Ships with Google Play Services | $(have com.google.android.gms) |"
write "| Bootloader | flash.locked=$(prop ro.boot.flash.locked), verifiedboot=$(prop ro.boot.verifiedbootstate) |"
write "| SELinux | $(sh getenforce) |"
write "| Root (su on PATH) | $(sh 'command -v su >/dev/null && echo yes || echo no') |"
write ""
IMM="$(ver com.immortal.launcher)"
write "## Repurposing setup (what's been flashed on, if anything)"
write "_Side-loaded, owner-specific — listed for context, not a device trait._"
write ""
write "| | |"
write "|---|---|"
write "| Custom launcher | $([ -n "$IMM" ] && echo "Immortal $IMM" || echo "none detected (stock launcher)") |"
write ""
write "## Sensors"
write '```'
sh 'dumpsys sensorservice | grep -oE "android.sensor.[a-z_]+" | sort -u | sed "s/android.sensor.//"' >> "$OUT"
write '```'
write ""
write "## Permission census ($N_TOTAL platform permissions)"
write "What a **sideloaded (non-platform-signed) app** can obtain on this build:"
write ""
write "| Reachability | Count |"
write "|---|---|"
write "| Normal — auto-granted | $N_NORMAL |"
write "| Dangerous — runtime prompt | $N_DANGER |"
write "| **Development — \`adb pm grant\` (elevated)** | **$N_DEV** |"
write "| Signature/privileged walls | $N_WALL |"
write ""
write "<details><summary>The \`development\` (adb-grantable) permissions — the useful elevated set</summary>"
write ""
write "$DEV_LIST"
write ""
write "</details>"
write ""
write "## Active resource overlays (RROs — vendor theming/config)"
write '```'
sh 'cmd overlay list' | grep -E '^\[x\]|^\[ \]' >> "$OUT" 2>/dev/null || sh 'cmd overlay list' >> "$OUT"
write '```'
write ""
write "## Cameras (who holds the hardware)"
write '```'
sh 'dumpsys media.camera | grep -iE "number of (normal )?camera devices:|Device [0-9] maps|Client Package Name" | head -12' >> "$OUT"
write '```'
write ""
write "---"
write "_Submitted from collect.sh. Read-only; no personal data._"

echo "Wrote $OUT"
echo "------------------------------------------------------------------"
cat "$OUT"

# ---- one-click submit ------------------------------------------------------
# We copy the report to your clipboard and open a pre-filled GitHub issue, so
# you just paste + click Submit. We deliberately DON'T auto-post (that'd file
# an issue on your behalf without you seeing it) — you stay in control.
REPO="thefloppytaco/portal-device-db"
urlenc() { python3 -c 'import sys,urllib.parse;print(urllib.parse.quote(sys.stdin.read()),end="")' 2>/dev/null; }
ISSUE_URL="https://github.com/${REPO}/issues/new?template=device-report.yml"
if command -v python3 >/dev/null 2>&1; then
  ISSUE_URL="${ISSUE_URL}&title=$(printf '[Device] %s — %s' "$MODEL" "$DEVICE" | urlenc)&model=$(printf '%s' "$MODEL" | urlenc)"
fi

COPIED=""
if   command -v pbcopy  >/dev/null 2>&1; then pbcopy < "$OUT"  && COPIED=1   # macOS
elif command -v xclip   >/dev/null 2>&1; then xclip -selection clipboard < "$OUT" && COPIED=1  # Linux/X11
elif command -v wl-copy >/dev/null 2>&1; then wl-copy < "$OUT" && COPIED=1   # Linux/Wayland
fi

echo
echo "================================================================="
if   command -v open     >/dev/null 2>&1; then open "$ISSUE_URL"
elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$ISSUE_URL" >/dev/null 2>&1
else echo "To submit, open: $ISSUE_URL"
fi
if [ -n "$COPIED" ]; then
  echo "✅ Report copied to your clipboard + a pre-filled issue opened in your browser."
  echo "   Paste it into the 'collect.sh report' box and click Submit. Thank you!"
else
  echo "✅ A pre-filled issue opened in your browser. Paste the contents of:"
  echo "      $OUT"
  echo "   into the 'collect.sh report' box and click Submit. Thank you!"
fi
echo "================================================================="
